version: '3.2'

services:
  openvas:
    build: .
    restart: unless-stopped
    volumes:
      - ./gvmd:/usr/local/var/lib/gvm/gvmd
    ports:
      - 443:443
    depends_on:
      - psql
      - redis

  psql:
    build: postgres-build/
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: openvas
      POSTGRES_DB: gvmd
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: redis
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
